name    'ghoneycutt-nfs'
version '1.3.0'
source 'git://github.com/ghoneycutt/puppet-module-nfs.git'
author 'ghoneycutt'
license 'Apache License, Version 2.0'
summary 'Manage NFS'
description 'Manage NFS for client and server, including idmap'
project_page 'https://github.com/ghoneycutt/puppet-module-nfs'

dependency 'ghoneycutt/common',  '1.x'
dependency 'ghoneycutt/rpcbind', '1.x'
dependency 'ghoneycutt/types',   '>= 1.0.0'
dependency 'puppetlabs/stdlib',  '3.2.x'
