name    'ghoneycutt-nfs'
version '1.0.0'
source 'git://github.com/ghoneycutt/puppet-module-nfs.git'
author 'ghoneycutt'
license 'Apache License, Version 2.0'
summary 'Manage NFS'
description 'Manage NFS for client and server, including idmap'
project_page 'https://github.com/ghoneycutt/puppet-module-nfs'

dependency 'puppetlabs/stdlib', '3.2.x'
dependency 'ghoneycutt/rpcbind', '>= 0.1.0'
